'use strict';
// Shared packaging and initializer support; no host generator dependencies.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const yaml = require('js-yaml');
const { walk } = require('./package-provenance');
const ROOT = path.resolve(__dirname, '..');
const sha256 = buffer => crypto.createHash('sha256').update(buffer).digest('hex');

function support(surface, rootDir = ROOT) {
  if (surface === 'claude') throw Error('Use build() for the Claude Code plugin');
  const files = new Map();
  for (const rel of ['aldc_context_doctor.py', 'README.md']) {
    const dest = surface === 'codex' ? (rel.endsWith('.py') ? 'skills/aldc/scripts/' + rel : 'skills/aldc/references/doctor.md') : 'tools/context-doctor/' + rel;
    let body = fs.readFileSync(path.join(rootDir, 'tools/context-doctor', rel), 'utf8');
    if (surface === 'codex' && rel === 'README.md') body = body.replaceAll('../../docs/templates/', 'templates/');
    files.set(dest, body);
  }
  for (const rel of ['bcquality/precondition_hook.sh', 'bcquality/precondition_hook.ps1', 'bcquality/config.js', 'bcquality/index-state.js', 'bcquality/validate_evidence.py', 'bcquality/install.sh', 'bcquality/install.ps1', 'aldc-validate/package.json', 'aldc-validate/index.js']) {
    const dest = surface === 'codex' ? 'skills/aldc/scripts/' + rel : 'tools/' + rel;
    files.set(dest, fs.readFileSync(path.join(rootDir, 'tools', rel), 'utf8'));
  }
  for (const name of ['install-transaction.js', 'package-provenance.js']) files.set(`scripts/${name}`, fs.readFileSync(path.join(rootDir, 'scripts', name), 'utf8'));
  files.set('scripts/init.js', fs.readFileSync(path.join(rootDir, 'scripts/init-plugin.js'), 'utf8'));
  const plansRoot = plansRootFor(rootDir, surface);
  // Templates stay byte-identical to canonical on every surface; the seed lands at
  // `${plansRoot}/memory.md`, which is what actually places it.
  for (const p of walk(rootDir, 'docs/templates')) files.set(p, fs.readFileSync(path.join(rootDir, p), 'utf8'));
  files.set('templates/memory-template.md', fs.readFileSync(path.join(rootDir, 'docs/templates/memory-template.md'), 'utf8'));
  files.set('surface.json', JSON.stringify({ surface, plansRoot }, null, 2) + '\n');
  files.set('project-guidance.md', projectGuidance(surface, plansRoot));
  // Consumers (tools/bcquality/config.js, aldc-validate, install.js) read the root
  // from `aldc.yaml -> plans.root`. Only a surface that moves off the canonical root
  // needs to declare it; the CLI keeps .github/plans and its consumers already default there.
  const auditsRoot = auditsRootFor(rootDir, surface);
  if (plansRoot !== CANONICAL_PLANS_ROOT || auditsRoot !== CANONICAL_AUDITS_ROOT) {
    files.set('aldc.yaml', surfaceAldcYaml(rootDir, surface, plansRoot, auditsRoot));
  }
  return files;
}

const CANONICAL_PLANS_ROOT = '.github/plans';
const CANONICAL_AUDITS_ROOT = '.github/audits';

/** The `aldc.yaml` a non-Claude plugin ships so its work-product roots are declared, not implied. */
function surfaceAldcYaml(rootDir, surface, plansRoot, auditsRoot) {
  const sourceRel = 'aldc.yaml';
  const name = surface === 'codex' ? 'Codex' : 'Copilot CLI';
  const raw = fs.readFileSync(path.join(rootDir, sourceRel));
  const text = raw.toString('utf8')
    .replace(/^toolkitRoot:.*$/m, 'toolkitRoot: "."')
    .replace(/^(plans:\n\s+root:\s*)"[^"]*"/m, `$1"${plansRoot}"`)
    .replace(/^(audits:\n\s+root:\s*)"[^"]*"/m, `$1"${auditsRoot}"`);
  return `# ALDC — ${name} toolkit root configuration.\n` +
    `# Generated by scripts/plugin-runtime.js from the repository aldc.yaml\n` +
    `# (sha256 ${sha256(raw)}). Do not edit; edit the source and re-run the generator.\n` +
    `#\n` +
    `# Requirement artifacts live under ${plansRoot} and audit reports under ${auditsRoot}\n` +
    `# in a ${name} deployment (plans.root and audits.root below). The canonical file keeps\n` +
    `# ${CANONICAL_PLANS_ROOT} and ${CANONICAL_AUDITS_ROOT}, which is correct for the Copilot\n` +
    `# deployment and the VS Code extension package.\n\n${text}`;
}

function projectGuidance(surface, plansRoot) {
  const base = surface === 'codex'
    ? `Use the ALDC skill at .agents/skills/aldc/SKILL.md for Business Central development. Read the relevant role, workflow and AL rules there before acting. Preserve approved plans and ${plansRoot}/memory.md. Human gates and the current session authorization apply.\n`
    : `This project uses the ALDC ${surface === 'claude' ? 'Claude Code' : 'Copilot CLI'} plugin. Discover its installed agents, skills and workflows and read their full contracts. Use al-architect for design, al-spec-agent (via al-spec-create) for specification, al-developer for implementation and al-conductor for TDD orchestration. Keep approved artifacts and memory in ${plansRoot}/. Read the ${surface === 'claude' ? '.claude/rules' : '.github/instructions'} AL rules for the affected files. Host loading and tool availability must be observed; installation does not certify them. Preserve material human gates.\n`;
  return base +
    `At session start or after an environment change, run the read-only ALDC Doctor with an available Python 3.9+ interpreter. Use --workspace for this project and --host ${surface}; --toolkit names the installed plugin root (or this project for Codex local bootstrap). See ${surface === 'codex' ? '.agents/skills/aldc/references/doctor.md; script .agents/skills/aldc/scripts/aldc_context_doctor.py' : 'tools/context-doctor/README.md and aldc_context_doctor.py in the installed plugin'}. Repeat only affected --operation checks. File presence and exit 0 do not certify host loading or execution. Do not install an interpreter automatically.\n`;
}

const SURFACE_PLANS_PREFIX = { claude: '.claude/', codex: '.agents/' };
function plansRootFor(rootDir, surface = 'claude') {
  const cfg = yaml.load(fs.readFileSync(path.join(rootDir, 'aldc.yaml'), 'utf8')) || {};
  const canonical = cfg.plans?.root || '.github/plans';
  const prefix = SURFACE_PLANS_PREFIX[surface];
  return prefix ? canonical.replace(/^\.github\//, prefix) : canonical;
}

// Dredd's audit reports are the other work product. Only Codex relocates them: the
// Claude Code plugin moved its plans in #104 but nothing decided the same for its
// audits, and inventing that here would change a surface nobody asked about.
const SURFACE_AUDITS_PREFIX = { codex: '.agents/' };
function auditsRootFor(rootDir, surface = 'codex') {
  const cfg = yaml.load(fs.readFileSync(path.join(rootDir, 'aldc.yaml'), 'utf8')) || {};
  const canonical = cfg.audits?.root || '.github/audits';
  const prefix = SURFACE_AUDITS_PREFIX[surface];
  return prefix ? canonical.replace(/^\.github\//, prefix) : canonical;
}


module.exports = { support, projectGuidance, plansRootFor, auditsRootFor };
